#!/usr/bin/env node
var config = require('./config/site')
var app = require('./app');

app.set('port', process.env.PORT || config.port);

var server = app.listen(app.get('port'),function(){
	console.log('Express server listening on port '+server.address().port);
});